
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/bc038f95-38ce-4098-9525-59df3f429ac2";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/bc038f95-38ce-4098-9525-59df3f429ac2";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C4BD-B34A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/bc038f95-38ce-4098-9525-59df3f429ac2";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/bc038f95-38ce-4098-9525-59df3f429ac2";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/bc038f95-38ce-4098-9525-59df3f429ac2";
      fsType = "btrfs";
      options = [ "subvol=@persist" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/bc038f95-38ce-4098-9525-59df3f429ac2";
      fsType = "btrfs";
      options = [ "subvol=@swap" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/bc038f95-38ce-4098-9525-59df3f429ac2";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
