return {
	"lmantw/themify.nvim",
	lazy = false,
	priority = 999,
	dependencies = { "rktjmp/lush.nvim" },
	config = function()
		require("themify").setup({
			async = true,
			activity = true,
			{ "folke/tokyonight.nvim", blacklist = { "tokyonight-day", "tokyonight" } },
			{ "catppuccin/nvim", blacklist = { "catppuccin", "catppuccin-latte" } },
			{ "rebelot/kanagawa.nvim", blacklist = { "kanagawa", "kanagawa-lotus" } },
			{ "navarasu/onedark.nvim" },
			{ "bluz71/vim-nightfly-colors" },
			{ "gbprod/nord.nvim" },
			{ "rmehri01/onenord.nvim", blacklist = { "onenord-light" } },
			{ "savq/melange-nvim" },
			{ "Shatur/neovim-ayu", blacklist = { "ayu", "ayu-light" } },
			{ "ellisonleao/gruvbox.nvim" },
			{ "oxfist/night-owl.nvim" },
			{ "rafamadriz/neon" },
			{ "Mofiqul/vscode.nvim" },
			{ "askfiy/visual_studio_code" },
			{ "marko-cerovac/material.nvim", blacklist = { "material", "material-lighter" } },
			{ "sainnhe/sonokai" },
			{ "nvimdev/zephyr-nvim" },
			{ "sainnhe/edge" },
			{ "tanvirtin/monokai.nvim" },
			{ "Mofiqul/dracula.nvim" },
			{ "tiagovla/tokyodark.nvim" },
			{ "cpea2506/one_monokai.nvim" },
		})
	end,
}
